# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsix():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsix(self):
    self.driver.get("https://demo.guru99.com/V4/manager/deleteAccountInput.php")
    self.driver.find_element(By.NAME, "accountno").click()
    self.driver.find_element(By.NAME, "accountno").send_keys(" ")
    assert self.driver.switch_to.alert.text == "Account Number must not be blank"
    self.driver.find_element(By.NAME, "accountno").send_keys("123Acc123")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) > td:nth-child(2)").click()
    assert self.driver.switch_to.alert.text == "Characters are not allowed"
    self.driver.find_element(By.NAME, "accountno").click()
    self.driver.find_element(By.NAME, "accountno").send_keys("123!@#")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) > td:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) > td:nth-child(2)").click()
    assert self.driver.switch_to.alert.text == "Special characters are not allowed"
    self.driver.find_element(By.NAME, "accountno").click()
    self.driver.find_element(By.NAME, "accountno").send_keys("123 12")
    self.driver.find_element(By.CSS_SELECTOR, "td tr:nth-child(1) > td").click()
    assert self.driver.switch_to.alert.text == "Characters are not allowed"
    self.driver.find_element(By.NAME, "accountno").click()
    self.driver.find_element(By.NAME, "accountno").send_keys(" ")
    assert self.driver.switch_to.alert.text == "Characters are not allowed"
    self.driver.find_element(By.NAME, "accountno").click()
    self.driver.find_element(By.NAME, "accountno").send_keys("121525")
    self.driver.find_element(By.NAME, "AccSubmit").click()
    assert self.driver.switch_to.alert.text == "Do you really want to delete this Account?"
    self.driver.switch_to.alert.accept()
    assert self.driver.switch_to.alert.text == "demo.guru99.com is currently unable to handle this request."
    self.driver.find_element(By.NAME, "accountno").click()
    self.driver.find_element(By.NAME, "accountno").send_keys("12345")
    self.driver.find_element(By.NAME, "AccSubmit").click()
    assert self.driver.switch_to.alert.text == "Do you really want to delete this Account?"
    self.driver.switch_to.alert.accept()
    assert self.driver.switch_to.alert.text == "Account does not exist"
    self.driver.find_element(By.NAME, "accountno").click()
    self.driver.find_element(By.NAME, "accountno").send_keys("qwer12345")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(11) > td:nth-child(2)").click()
    self.driver.find_element(By.NAME, "res").click()
  
if __name__ == "__main__":
    pytest.main()