# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestVerifynamefield():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def login_to_bank(self):
        self.driver.get("https://demo.guru99.com/V4/index.php")
        self.driver.find_element(By.NAME, "uid").click()
        self.driver.find_element(By.NAME, "uid").send_keys("mngr492649")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("anyguqE")
        self.driver.find_element(By.NAME, "btnLogin").click()

    def test_one(self):
        self.login_to_bank()
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message").text == "Customer name must not be blank"

    def test_two(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("1234")
        self.driver.find_element(By.NAME, "name").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message").text == "Numbers are not allowed"

    def test_three(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("name1234")
        self.driver.find_element(
            By.CSS_SELECTOR, "tbody:nth-child(2) > tr > td").click()
        assert self.driver.find_element(
            By.ID, "message").text == "Numbers are not allowed"

    def test_four(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("name!@#")
        self.driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(4) > td:nth-child(2)").click()
        assert self.driver.find_element(
            By.ID, "message").text == "Special characters are not allowed"

    def test_five(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys(" ")
        self.driver.find_element(By.NAME, "name").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message").text == "First character can not have space"

    def test_six(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "addr").click()
        self.driver.find_element(By.NAME, "addr").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message3").text == "Address Field must not be blank"

    def test_seven(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "addr").click()
        self.driver.find_element(By.NAME, "addr").send_keys(" ")
        self.driver.find_element(By.NAME, "addr").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message3").text == "First character can not have space"

    def test_nine(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message4").text == "City Field must not be blank"

    def test_eight(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys("1234")
        self.driver.find_element(By.NAME, "city").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message4").text == "Numbers are not allowed"

    def test_ten(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys("city1234")
        self.driver.find_element(By.NAME, "city").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message4").text == "Numbers are not allowed"

    def test_eleven(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys("city!@#")
        self.driver.find_element(By.NAME, "city").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message4").text == "Special characters are not allowed"

    def test_eleven_point_one(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys("!@#")
        self.driver.find_element(By.NAME, "city").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message4").text == "Special characters are not allowed"

    def test_twelve(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys(" ")
        self.driver.find_element(By.NAME, "city").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message4").text == "First character can not have space"

    def test_thirteen(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "state").click()
        self.driver.find_element(By.NAME, "state").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message5").text == "State must not be blank"

    def test_fourteen(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "state").click()
        self.driver.find_element(By.NAME, "state").send_keys("1234")
        self.driver.find_element(By.NAME, "state").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message5").text == "Numbers are not allowed"

    def test_fifteen(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "state").click()
        self.driver.find_element(By.NAME, "state").send_keys("state123")
        self.driver.find_element(By.NAME, "state").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message5").text == "Numbers are not allowed"

    def test_sixteen(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "state").click()
        self.driver.find_element(By.NAME, "state").send_keys("City!@#")
        self.driver.find_element(By.NAME, "state").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message5").text == "Special characters are not allowed"

    def test_eightteen(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "state").click()
        self.driver.find_element(By.NAME, "state").send_keys(" ")
        self.driver.find_element(By.ID, "message5").click()
        self.driver.find_element(By.NAME, "state").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message5").text == "First character can not have space"

    def test_nineteen(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "pinno").click()
        self.driver.find_element(By.NAME, "pinno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message6").text == "PIN Code must not be blank"

    def test_twinty(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "pinno").click()
        self.driver.find_element(By.NAME, "pinno").send_keys("1234PIN")
        self.driver.find_element(By.NAME, "pinno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message6").text == "Characters are not allowed"

    def test_twintyone(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "pinno").click()
        self.driver.find_element(By.NAME, "pinno").send_keys("12")
        self.driver.find_element(By.NAME, "pinno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message6").text == "PIN Code must have 6 Digits"

    def test_twintttwo(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "pinno").click()
        self.driver.find_element(By.NAME, "pinno").send_keys("123")
        self.driver.find_element(By.NAME, "pinno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message6").text == "PIN Code must have 6 Digits"

    def test_twintthree(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "pinno").click()
        self.driver.find_element(By.NAME, "pinno").send_keys("!@#")
        self.driver.find_element(By.NAME, "pinno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message6").text == "Special characters are not allowed"

    def test_twintyfour(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "pinno").click()
        self.driver.find_element(By.NAME, "pinno").send_keys(" ")
        self.driver.find_element(By.NAME, "pinno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message6").text == "First character can not have space"

    def test_twintyfour(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "pinno").click()
        self.driver.find_element(By.NAME, "pinno").send_keys("12 45")
        self.driver.find_element(By.NAME, "pinno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message6").text == "Characters are not allowed"

    def test_twintyfive(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "telephoneno").click()
        self.driver.find_element(By.NAME, "telephoneno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message7").text == "Mobile no must not be blank"

    def test_twintyfive(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "telephoneno").click()
        self.driver.find_element(By.NAME, "telephoneno").send_keys(" ")
        self.driver.find_element(By.NAME, "telephoneno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message7").text == "First character can not have space"

    def test_twintysix(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "telephoneno").click()
        self.driver.find_element(By.NAME, "telephoneno").send_keys("123 123")
        self.driver.find_element(By.NAME, "telephoneno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message7").text == "Characters are not allowed"

    def test_twintyseven(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "telephoneno").click()
        self.driver.find_element(
            By.NAME, "telephoneno").send_keys("886636!@12")
        self.driver.find_element(By.NAME, "telephoneno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message7").text == "Special characters are not allowed"

    def test_twintyeight(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "telephoneno").click()
        self.driver.find_element(
            By.NAME, "telephoneno").send_keys("!@88662682")
        self.driver.find_element(By.NAME, "telephoneno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message7").text == "Special characters are not allowed"

    def test_twintynine(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "telephoneno").click()
        self.driver.find_element(
            By.NAME, "telephoneno").send_keys("88663682!@")
        self.driver.find_element(By.NAME, "telephoneno").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message7").text == "Special characters are not allowed"

    def test_thirty(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "emailid").click()
        self.driver.find_element(By.NAME, "emailid").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message9").text == "Email-ID must not be blank"

    def test_thirtyone(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "emailid").click()
        self.driver.find_element(By.NAME, "emailid").send_keys("guru99@gmail")
        self.driver.find_element(By.NAME, "emailid").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message9").text == "Email-ID is not valid"

    def test_thirtytwo(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "emailid").click()
        self.driver.find_element(By.NAME, "emailid").send_keys("guru99")
        self.driver.find_element(By.NAME, "emailid").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message9").text == "Email-ID is not valid"

    def test_thirtythree(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "emailid").click()
        self.driver.find_element(By.NAME, "emailid").send_keys("Guru99@")
        self.driver.find_element(By.NAME, "emailid").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message9").text == "Email-ID is not valid"

    def test_thirtyfour(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "emailid").click()
        self.driver.find_element(By.NAME, "emailid").send_keys("guru99@gmail.")
        self.driver.find_element(By.NAME, "emailid").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message9").text == "Email-ID is not valid"

    def test_thirtyfive(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "emailid").click()
        self.driver.find_element(
            By.NAME, "emailid").send_keys("guru99gmail.com")
        self.driver.find_element(By.NAME, "emailid").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message9").text == "Email-ID is not valid"

    def test_thirtysix(self):
        self.driver.get(
            "https://demo.guru99.com/V4/manager/addcustomerpage.php")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys(Keys.TAB)
        assert self.driver.find_element(
            By.ID, "message18").text == "Password must not be blank"
